spring:
  application:
    name: checkout-hotmart
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          # ativando conexao TLS para protecao
          starttls.enable: true
          starttls.required: true


server:
  port: 8081
  error:
    include-message: always

wiremock-cloud: https://og9g7.wiremockapi.cloud/

